export const deleteBtn: string;
export const headerDropdownBtn: string;
export const headerDropdownContainer: string;
export const headerDropdownContent: string;
export const headerLogo: string;
export const headerMenuContainer: string;
export const logoutBtn: string;
export const myPageImgBtn: string;
export const root: string;
